package questions;

public class Question2
{
	/*
	 * Each new term in the Fibonacci sequence is generated by adding the previous
	 * two terms. By starting with 1 and 2, the first 10 terms will be:
	 *
	 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
	 *
	 * By considering the terms in the Fibonacci sequence whose values do not exceed
	 * four million, find the sum of the even-valued terms.
	 */


	public static void main(String args[])

	{
		int count=1;
		int t1=0;
		int t2=1;
		int sum = 0;
		int result=0;
		while(count<100)
		{
			sum =t1+t2;
			t1=t2;
			t2=sum;

			if (sum%2==0)
			{
				if(result<4000000)
				{
					result=result+sum;
				}

			}

			count++;
		}
		System.out.println(result);



	}

}
